// Mocks generated by Mockito 5.4.6 from annotations
// in cc_workout_app/test/features/rep_maxes/screens/rep_maxes_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cc_workout_app/features/rep_maxes/domain/entities/rep_max.dart'
    as _i4;
import 'package:cc_workout_app/features/rep_maxes/domain/services/rep_max_calculation_service.dart'
    as _i2;
import 'package:cc_workout_app/shared/models/lift_type.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RepMaxCalculationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRepMaxCalculationService extends _i1.Mock
    implements _i2.RepMaxCalculationService {
  MockRepMaxCalculationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.RepMax>> calculateAllRepMaxes() =>
      (super.noSuchMethod(
            Invocation.method(#calculateAllRepMaxes, []),
            returnValue: _i3.Future<List<_i4.RepMax>>.value(<_i4.RepMax>[]),
          )
          as _i3.Future<List<_i4.RepMax>>);

  @override
  _i3.Future<Map<_i5.LiftType, List<_i4.RepMax>>> calculateRepMaxesByLift() =>
      (super.noSuchMethod(
            Invocation.method(#calculateRepMaxesByLift, []),
            returnValue: _i3.Future<Map<_i5.LiftType, List<_i4.RepMax>>>.value(
              <_i5.LiftType, List<_i4.RepMax>>{},
            ),
          )
          as _i3.Future<Map<_i5.LiftType, List<_i4.RepMax>>>);

  @override
  _i3.Future<List<_i4.RepMax>> calculateRepMaxesForLift(
    _i5.LiftType? liftType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#calculateRepMaxesForLift, [liftType]),
            returnValue: _i3.Future<List<_i4.RepMax>>.value(<_i4.RepMax>[]),
          )
          as _i3.Future<List<_i4.RepMax>>);

  @override
  _i3.Future<_i4.RepMax?> getRepMaxForLiftAndReps(
    _i5.LiftType? liftType,
    int? reps,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRepMaxForLiftAndReps, [liftType, reps]),
            returnValue: _i3.Future<_i4.RepMax?>.value(),
          )
          as _i3.Future<_i4.RepMax?>);

  @override
  _i3.Future<Map<int, _i4.RepMax>> getRepMaxTableForLift(
    _i5.LiftType? liftType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRepMaxTableForLift, [liftType]),
            returnValue: _i3.Future<Map<int, _i4.RepMax>>.value(
              <int, _i4.RepMax>{},
            ),
          )
          as _i3.Future<Map<int, _i4.RepMax>>);

  @override
  _i3.Future<Map<_i5.LiftType, Map<int, _i4.RepMax>>> getFullRepMaxTable() =>
      (super.noSuchMethod(
            Invocation.method(#getFullRepMaxTable, []),
            returnValue:
                _i3.Future<Map<_i5.LiftType, Map<int, _i4.RepMax>>>.value(
                  <_i5.LiftType, Map<int, _i4.RepMax>>{},
                ),
          )
          as _i3.Future<Map<_i5.LiftType, Map<int, _i4.RepMax>>>);
}
